/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SignupRouteImport } from './../routes/signup'
import { Route as LoginRouteImport } from './../routes/login'
import { Route as ContactRouteImport } from './../routes/contact'
import { Route as ChatRouteImport } from './../routes/chat'
import { Route as AboutRouteImport } from './../routes/about'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as MarketplaceIndexRouteImport } from './../routes/marketplace.index'
import { Route as LostFoundIndexRouteImport } from './../routes/lost-found.index'
import { Route as EventsIndexRouteImport } from './../routes/events.index'
import { Route as MarketplaceSellRouteImport } from './../routes/marketplace.sell'
import { Route as MarketplaceIdRouteImport } from './../routes/marketplace.$id'
import { Route as LostFoundReportLostRouteImport } from './../routes/lost-found.report-lost'
import { Route as LostFoundReportFoundRouteImport } from './../routes/lost-found.report-found'
import { Route as EventsCreateRouteImport } from './../routes/events.create'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
})
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
})
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
})
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
})
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
})
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
})
const LostFoundIndexRoute = LostFoundIndexRouteImport.update({
  id: '/lost-found/',
  path: '/lost-found/',
  getParentRoute: () => rootRouteImport,
})
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
})
const MarketplaceSellRoute = MarketplaceSellRouteImport.update({
  id: '/marketplace/sell',
  path: '/marketplace/sell',
  getParentRoute: () => rootRouteImport,
})
const MarketplaceIdRoute = MarketplaceIdRouteImport.update({
  id: '/marketplace/$id',
  path: '/marketplace/$id',
  getParentRoute: () => rootRouteImport,
})
const LostFoundReportLostRoute = LostFoundReportLostRouteImport.update({
  id: '/lost-found/report-lost',
  path: '/lost-found/report-lost',
  getParentRoute: () => rootRouteImport,
})
const LostFoundReportFoundRoute = LostFoundReportFoundRouteImport.update({
  id: '/lost-found/report-found',
  path: '/lost-found/report-found',
  getParentRoute: () => rootRouteImport,
})
const EventsCreateRoute = EventsCreateRouteImport.update({
  id: '/events/create',
  path: '/events/create',
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChatRoute: ChatRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  EventsCreateRoute: EventsCreateRoute,
  LostFoundReportFoundRoute: LostFoundReportFoundRoute,
  LostFoundReportLostRoute: LostFoundReportLostRoute,
  MarketplaceIdRoute: MarketplaceIdRoute,
  MarketplaceSellRoute: MarketplaceSellRoute,
  EventsIndexRoute: EventsIndexRoute,
  LostFoundIndexRoute: LostFoundIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)

import type { getRouter } from '../router.jsx'
import type { startInstance } from '../start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
