spring.application.name=OneCampus

spring.datasource.url=jdbc:postgresql://ep-tiny-tooth-za4o1r2z.c-2.eu-west-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

jwt.private-key=${JWT_PRIVATE_KEY}
jwt.public-key=${JWT_PUBLIC_KEY}
jwt.access-token-ttl-minutes=15
jwt.refresh-token-ttl-days=7

logging.level.org.springframework.jdbc=DEBUG